# Generated by Django 3.1.4 on 2021-02-02 07:25

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Representado',
            fields=[
                ('codigo_qr', models.CharField(default='', max_length=50, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=250)),
                ('apellido', models.CharField(max_length=250)),
                ('edad', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Representante',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cedula', models.CharField(max_length=10, null=True)),
                ('nombre', models.CharField(max_length=250)),
                ('apellido', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Relacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('representado', models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, to='api.representado')),
                ('representante', models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, to='api.representante')),
            ],
            options={
                'unique_together': {('representante', 'representado')},
            },
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.ImageField(blank=True, null=True, upload_to='(%Y_%m_%d)/')),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('observacion', models.TextField(blank=True, default='', null=True)),
                ('periodo', models.CharField(default='', max_length=25)),
                ('revisado', models.BooleanField(default=False, null=True)),
                ('punt_prote', models.IntegerField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('punt_veg', models.IntegerField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('punt_carb', models.IntegerField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('representado', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='api.representado')),
                ('representante', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='api.representante')),
            ],
            options={
                'unique_together': {('periodo', 'representado')},
            },
        ),
    ]
