# Generated by Django 3.1.4 on 2021-02-02 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20210202_0249'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='puntuacion_general',
            field=models.IntegerField(blank=True, choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10)], default=0, null=True),
        ),
    ]
